### ISSUE TITLE
Request "get_history" should not be cached by IE

### ISSUE THREAD

**Issue by hknutzen** [hknutzen/Netspoc-Web#20]
A request ".../get_history?active_owner=x" is sent, to get current list of avaliable historie entries.
If user selects combobox "Stand:", Firefox always retrieves the newest list.
But IE 9 uses a cached copy and hence shows stale list of history entries.

The request type should be changed from GET to POST to prevent caching.

**Comment by orrence** [comment]
Fixed by commit 2b08ae155c3fb347b016677e84f3084b95d90456
