### ISSUE TITLE
Search for ports should act on numbers and ranges, not on strings

### ISSUE THREAD

**Issue by hknutzen** [hknutzen/Netspoc-Web#27]
When searching for ports, currently a sub-string search is done.
Example: Searching for port 102 also finds port 1024.
Proposal:
Comparison should be done numerically and port ranges should be supported.
Examples:
- 102 should find 102 and all ranges including port 102, e.g. 100-120
- 100-120 should find 
  - all ports and ranges inside this range, e.g. 102 or 105-110
  - ranges including this range,  e.g. 1-1024
  - ranges overlapping this range, e.g. 110-130

Options "Übergeordnete Netze einbeziehen" and "Enthaltene Netze einbeziehen" shoud control, if sub-ranges / enclosing ranges should be searched or not.

**Comment by orrence** [comment]
Implemented by commit 3f306efdd2eef094b7eb579cb3ecefaded9e2e54
