### ISSUE TITLE
Services can't be seen by owners that should see them

### ISSUE THREAD

**Issue by orrence** [hknutzen/Netspoc-Web#29]
This is an old bug. Sometimes there are several owners that have the same network in the list of own networks. All those owners should see all the services that have to do with that network, but that is sometimes not the case.

An old example found by Heinz Knutzen:
"Das network:010_068_008_000_LAN_LIT gehört dem owner = DA_MVS_Basisbetrieb,
liegt aber in der Sicherheitszone des owner:DA_FHH-Net.
Daher ist das Netz in „Eigene Netze“ von beiden Ownern sichtbar.

Daher sollten auch alle Dienste, die sich auf dieses Netz beziehen, für beide Owner sichtbar sein.
Ist aber nicht so. (auf dem Produktions-Policy-Web)
Z.B. ist der service:B21_Transfer_Hausbankverfahren_SH
nur für DA_MVS_Basisbetrieb sichtbar,
aber nicht für DA_FHH-Net."

**Comment by hknutzen** [comment]
Has been fixed in hknutzen/Netspoc@8f705736b9da7962aa1ee5e77d279527516a29c7
